traveling/main/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView


urlpatterns = [

    path('', MainView.as_view(), name='main'),
    path('get_trip_details/<int:trip_id>/', get_trip_details, name='get_trip_details'),
    path('get_trip_details_profile/<int:trip_id>/', get_trip_details_profile, name='get_trip_details_profile'),
    path('register/', register, name='register'),
    path('profile_user/', ProfileUserView.as_view(), name='profile_user'),
    path('add_comment/', add_comment, name='add_comment'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('login/', login_view, name='login'),
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('city_suggestions/', city_suggestions, name='city_suggestions'),
    path('logout/', logout_view, name='logout'),
    path('add_trip/', add_trip, name='add_trip'),
    path('remove_passenger/', remove_passenger, name='remove_passenger'),
    path('add_passenger/<int:trip_id>/', add_passenger, name='add_passenger'),
    path('handle_passenger_request/<int:notification_id>/<str:action>/', handle_passenger_request, name='handle_passenger_request'),
    path('remove_passenger/<int:trip_id>/', remove_passenger, name='remove_passenger'),
    path('delete_trip/<int:trip_id>/', delete_trip, name='delete_trip'),
    path('leave_trip/<int:trip_id>/', leave_trip, name='leave_trip'),
    path('start_trip/<int:trip_id>/', start_trip, name='start_trip'),
    path('end_trip/<int:trip_id>/', end_trip, name='end_trip'),
    path('change_password/', change_password, name='change_password'),

              ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

traveling/traveling/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),

]

traveling/main/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime, timedelta

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    birth_date = models.DateField(blank=True, null=True)
    password = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    email = models.CharField(max_length=100)
    about_me = models.TextField(blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    gender = models.CharField(max_length=1, blank=True, null=True)

    def set_password(self, raw_password):
        self.password = make_password(raw_password)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Car(models.Model):
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    brand = models.CharField(max_length=255)
    model = models.CharField(max_length=255, blank=True, null=True)
    color = models.CharField(max_length=255, blank=True, null=True)
    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='cars')

    def __str__(self):
        return f"{self.brand} {self.model} ({self.color})"


class City(models.Model):
    name = models.CharField(max_length=255)


    def __str__(self):
        return f"{self.name}"

class Comment(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='received_comments')
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='authored_comments')
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

class Trip(models.Model):
    STATUS_CHOICES = [
        ('planned', 'Planned'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
    ]

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    departure_city = models.ForeignKey(City, related_name='departure_city', on_delete=models.CASCADE)
    destination_city = models.ForeignKey(City, related_name='destination_city', on_delete=models.CASCADE)
    car = models.ForeignKey(Car, related_name='trip_car', on_delete=models.CASCADE)
    departure_date = models.DateField()
    departure_time = models.TimeField()
    arrival_date = models.DateField(null=True, blank=True)
    arrival_time = models.TimeField()
    passengers = models.ManyToManyField(UserProfile, related_name='trip_passengers', blank=True)
    max_passengers = models.PositiveIntegerField(default=4)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    comment = models.TextField(blank=True, null=True)
    pending_passengers = models.ManyToManyField(UserProfile, related_name='pending_trips', blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='planned')


    def has_active_trip(self):
        return Trip.objects.filter(user=self, status__in=['planned', 'in_progress']).exists()
    def start_trip(self):
        self.status = 'in_progress'
        self.save()

    def end_trip(self):
        self.status = 'completed'
        self.save()
    @property
    def duration(self):
        if self.arrival_date and self.arrival_time:
            departure_datetime = datetime.combine(self.departure_date, self.departure_time)
            arrival_datetime = datetime.combine(self.arrival_date, self.arrival_time)
            return arrival_datetime - departure_datetime
        return None

    @property
    def duration_hours(self):
        duration = self.duration
        if duration:
            return duration.days * 24 + duration.seconds // 3600
        return None

    @property
    def duration_minutes(self):
        duration = self.duration
        if duration:
            return (duration.seconds // 60) % 60
        return None

    @property
    def duration_string(self):
        hours = self.duration_hours
        minutes = self.duration_minutes
        if hours is not None and minutes is not None:
            return f"{hours} ч {minutes} м"
        return None

    @property
    def is_full(self):
        return self.passengers.count() >= self.max_passengers

    def __str__(self):
        return f"Trip from {self.departure_city} to {self.destination_city} on {self.departure_date}"


class Notification(models.Model):
    recipient = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='notifications')
    sender = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='sent_notifications')
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, related_name='notifications')
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"Notification for {self.recipient.user.username}"

    def is_request_notification(self):
        return "хочет присоединиться к вашей поездке" in self.message

traveling/main/forms.py
import re

from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone

from .models import UserProfile, Comment
from django.forms.widgets import DateInput, RadioSelect

class UserProfileForm(forms.Form):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    phone_number = forms.CharField(max_length=20, required=False)
    email = forms.EmailField()
    about_me = forms.CharField(widget=forms.Textarea, required=False)
    avatar = forms.ImageField(required=False)


class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].widget = forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Старый пароль'
        })
        self.fields['new_password1'].widget = forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Новый пароль'
        })
        self.fields['new_password2'].widget = forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Повторите новый пароль'
        })

        self.fields['old_password'].label = ''
        self.fields['new_password1'].label = ''
        self.fields['new_password2'].label = ''
class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())


class UserRegistrationForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    phone = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name.split()) != 2:
            raise forms.ValidationError('Введите имя и фамилию.')
        return name

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с таким email уже существует.')
        return email

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        phone_regex = re.compile(r'^\+?\d{9,15}$')
        if not phone_regex.match(phone):
            raise forms.ValidationError('Введите корректный номер телефона.')
        return phone

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise forms.ValidationError('Пароль должен содержать как минимум 8 символов.')
        return password

class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)


from django import forms

class TripForm(forms.Form):
    car_name = forms.CharField(label='Название машины', max_length=100)
    departure_city = forms.CharField(
        label='Город отправления',
        max_length=100,
        widget=forms.TextInput(attrs={'id': 'departure', 'list': 'departure-list'})
    )
    destination_city = forms.CharField(
        label='Город прибытия',
        max_length=100,
        widget=forms.TextInput(attrs={'id': 'arrival', 'list': 'arrival-list'})
    )
    departure_time = forms.DateTimeField(
        label='Время отправления',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'})
    )
    arrival_time = forms.DateTimeField(
        label='Время прибытия',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'})
    )
    max_passengers = forms.IntegerField(
        label='Количество пассажиров',
        min_value=1,
        max_value=4
    )
    price = forms.DecimalField(
        label='Стоимость поездки',
        max_digits=10,
        decimal_places=0,
        min_value=50,
        max_value=15000,

    )
    comment = forms.CharField(
        label='Комментарий',
        widget=forms.Textarea(attrs={'placeholder': 'Введите комментарий', 'maxlength': 500}),
        required=False
    )
    car_image = forms.ImageField(label='Фото машины', required=False)


    def clean(self):
        cleaned_data = super().clean()

        departure_time = cleaned_data.get("departure_time")
        arrival_time = cleaned_data.get("arrival_time")
        departure_city = cleaned_data.get("departure_city")
        destination_city = cleaned_data.get("destination_city")

        if departure_time is None or arrival_time is None:
            raise forms.ValidationError("Время отправления и время прибытия должны быть заполнены.")

        if departure_time < timezone.now():
            raise forms.ValidationError("Время отправления не может быть в прошлом.")

        # Проверка, что дата и время отправления раньше даты и времени прибытия
        if departure_time >= arrival_time:
            raise forms.ValidationError("Дата и время отправления должны быть раньше даты и времени прибытия.")

        # Проверка, что города отправления и прибытия не совпадают
        if departure_city == destination_city:
            raise forms.ValidationError("Город отправления и город прибытия не могут совпадать.")

        return cleaned_data

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [ 'text']
        widgets = {

            'text': forms.Textarea(attrs={'placeholder': 'Введите ваш комментарий'}),
        }

traveling/main/templates/main/add_travel.html
{% extends "main/base.html" %}
{% load add_class %}
{% load static %}

{% block css %}
<!--suppress ALL -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'main/add.css' %}">
{% endblock %}

{% block title %}
Добавить поездку
{% endblock %}

{% block content %}

    <main class="main-container">
        <section class="trip-form">
            <h1>Добавить поездку</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-content">
            {% if form.errors %}
            <div class="error-messages">
                <ul>
                    {% for field, error_list in form.errors.items %}
                        {% for error in error_list %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <div class="input-group">
                <div class="full-width">
                    <label for="id_car_name">Название машины</label>
                    {{ form.car_name.errors }}
                    {{ form.car_name|add_class:"full-width-input" }}
                </div>
                <div class="form-group">
                    <div class="form-group-input">
                        <label for="departure">Город отправления</label>
                        {{ form.departure_city.errors }}
                        {{ form.departure_city|add_class:"half-width-input" }}
                        <datalist id="departure-list"></datalist>
                    </div>
                    <div class="form-group-input">
                        <label for="arrival">Город прибытия</label>
                        {{ form.destination_city.errors }}
                        {{ form.destination_city|add_class:"half-width-input" }}
                        <datalist id="arrival-list"></datalist>
                    </div>
                    <div class="form-group-input">
                        <label for="id_departure_time">Время отправления</label>
                        {{ form.departure_time.errors }}
                        {{ form.departure_time|add_class:"half-width-input" }}
                    </div>
                    <div class="form-group-input">
                        <label for="id_arrival_time">Время прибытия</label>
                        {{ form.arrival_time.errors }}
                        {{ form.arrival_time|add_class:"half-width-input" }}
                    </div>
                    <div class="form-group-input">
                        <label for="id_max_passengers">Количество пассажиров</label>
                        {{ form.max_passengers.errors }}
                        {{ form.max_passengers|add_class:"half-width-input" }}
                    </div>
                    <div class="form-group-input">
                        <label for="id_price">Стоимость поездки</label>
                        {{ form.price.errors }}
                        {{ form.price|add_class:"half-width-input" }}
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group textarea-grid">
            <label style="margin-bottom: -20px;">Комментарий</label>
            {{ form.comment.errors }}
            {{ form.comment|add_class:"full-width-textarea" }}
        </div>
        <span class="custom-span">Фотография автомобиля</span>
        <div class="photo-container" id="photoContainer">
            <div class="photo-preview-container" id="photoPreviewContainer"></div>
            <div class="photo-group" id="photoGroup">
                <input type="file" id="id_car_image" name="car_image" style="display: none;">
                <label for="id_car_image">
                    <img src="{% static 'img/add_photo.png' %}" alt="фото машины" class="car-photo" id="carPhotoLabel">
                </label>
                {{ form.car_image.errors }}
            </div>
        </div>
        <div class="form-actions">
            <button type="button" style="background-color: var(--color-darkblue)">Отменить</button>
            <button type="submit" style="background-color: var(--color-lightblue)">Опубликовать поездку</button>
        </div>
    </form>
        </section>
        <section class="section trips">
            <div class="trips-header" style="display: flex;">
                <h1>Мои поездки</h1>
                <button class="sort-button"><span>

                    </span>
                </button>
            </div>
            <div class="trip-list">
                {% for trip in trips %}
                <div class="trip-card trip-your">
                    <div class="trip-header">
                        <div class="trip-time">
                            <div class="time">{{ trip.departure_time|time:"H:i" }}</div>
                            <div class="svg-container">
                                <svg class="svg-large" width="63" height="14" viewBox="0 0 63 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <rect width="50" height="2" transform="translate(13 6)" fill="#444766"/>
                                    <path d="M7 0C3.14008 0 0 3.14008 0 7C0 10.8599 3.14008 14 7 14C10.8599 14 14 10.8599 14 7C14 3.14008 10.8599 0 7 0ZM7 12.8333C3.7835 12.8333 1.16667 10.2165 1.16667 7C1.16667 3.7835 3.7835 1.16667 7 1.16667C10.2165 1.16667 12.8333 3.7835 12.8333 7C12.8333 10.2165 10.2165 12.8333 7 12.8333ZM9.33333 7C9.33333 8.28858 8.28858 9.33333 7 9.33333C5.71142 9.33333 4.66667 8.28858 4.66667 7C4.66667 5.71142 5.71142 4.66667 7 4.66667C8.28858 4.66667 9.33333 5.71142 9.33333 7Z" fill="#444766"/>
                                </svg>
                                <svg class="svg-small" width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M7 0C3.14008 0 0 3.14008 0 7C0 10.8599 3.14008 14 7 14C10.8599 14 14 10.8599 14 7C14 3.14008 10.8599 0 7 0ZM7 12.8333C3.7835 12.8333 1.16667 10.2165 1.16667 7C1.16667 3.7835 3.7835 1.16667 7 1.16667C10.2165 1.16667 12.8333 3.7835 12.8333 7C12.8333 10.2165 10.2165 12.8333 7 12.8333ZM9.33333 7C9.33333 8.28858 8.28858 9.33333 7 9.33333C5.71142 9.33333 4.66667 8.28858 4.66667 7C4.66667 5.71142 5.71142 4.66667 7 4.66667C8.28858 4.66667 9.33333 5.71142 9.33333 7Z" fill="#444766"/>
                                </svg>
                                <div class="duration">
                                    {{ trip.duration_string }}
                                </div>
                                <svg class="svg-large" width="63" height="14" viewBox="0 0 63 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <rect width="50" height="2" transform="matrix(-1 0 0 -1 50 8)" fill="#444766"/>
                                    <path d="M55.998 14C59.858 14 62.998 10.8599 62.998 7C62.998 3.14008 59.858 0 55.998 0C52.1381 0 48.998 3.14008 48.998 7C48.998 10.8599 52.1381 14 55.998 14ZM55.998 1.16667C59.2145 1.16667 61.8314 3.7835 61.8314 7C61.8314 10.2165 59.2145 12.8333 55.998 12.8333C52.7815 12.8333 50.1647 10.2165 50.1647 7C50.1647 3.7835 52.7815 1.16667 55.998 1.16667ZM53.6647 7C53.6647 5.71142 54.7095 4.66667 55.998 4.66667C57.2866 4.66667 58.3314 5.71142 58.3314 7C58.3314 8.28858 57.2866 9.33333 55.998 9.33333C54.7095 9.33333 53.6647 8.28858 53.6647 7Z" fill="#444766"/>
                                </svg>
                                <svg class="svg-small" width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M7 0C3.14008 0 0 3.14008 0 7C0 10.8599 3.14008 14 7 14C10.8599 14 14 10.8599 14 7C14 3.14008 10.8599 0 7 0ZM7 12.8333C3.7835 12.8333 1.16667 10.2165 1.16667 7C1.16667 3.7835 3.7835 1.16667 7 1.16667C10.2165 1.16667 12.8333 3.7835 12.8333 7C12.8333 10.2165 10.2165 12.8333 7 12.8333ZM9.33333 7C9.33333 8.28858 8.28858 9.33333 7 9.33333C5.71142 9.33333 4.66667 8.28858 4.66667 7C4.66667 5.71142 5.71142 4.66667 7 4.66667C8.28858 4.66667 9.33333 5.71142 9.33333 7Z" fill="#444766"/>
                                </svg>
                            </div>
                            <div class="time">{{ trip.arrival_time|time:"H:i" }}</div>
                        </div>
                        <div class="trip-price"></div>
                        <div class="trip-locations">
                            <div class="location">{{ trip.departure_city }}</div>
                            <div class="location" style="text-align: right;">{{ trip.destination_city }}</div>
                        </div>
                    </div>
                    <div class="trip-details">
                        <div class="trip-date">{{ trip.departure_date|date:"d.m.Y" }}</div>
<!--                        <div class="trip-link"><button style="background-color: #DFE0EC; color: #5B62FF; font-weight: bold; font-size: 18px" href="#" id="openModalBtn">Детали поездки</button></div>-->
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>
        <div class="notification" id="notification">
          <span class="close" onclick="closeNotification()">&times;</span>
          <p id="notification-text">Вы можете добавить только 5 фотографий</p>
        </div>
        <div id="customModal" class="custom-modal">
            <div class="custom-modal-content">
                <span class="custom-close-btn">&times;</span>
                <div class="custom-driver-info">
                    <h3>О водителе</h3>
                    <img src="{% static 'img/women-high-fiving-car.png' %}" alt="Driver" class="custom-driver-photo">
                    <div class="custom-driver-details">
                        <h2>Имя фамилия <span class="custom-rating">4,9&#9733;</span></h2>
                        <p>описание водителя описание водителя описание водителя описание водителя</p>
                    </div>
                </div>
                <div class="custom-trip-details">
                    <h3>Детали поездки</h3>
                    <div class="custom-trip-info">
                        <div class="custom-from">
                            <p><strong>Откуда</strong></p>
                            <p>Тверь, ул. Можаского, д. 25</p>
                            <p>23 апреля, 23:46</p>
                            <p>2 пассажира</p>
                        </div>
                        <div class="custom-to">
                            <p><strong>Куда</strong></p>
                            <p>Москва, ул. Можаского, д. 25</p>
                            <p>23 апреля, 23:46</p>
                            <p>580 Р</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script src="{% static 'js/add_trip.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock content %}

traveling/main/templates/main/base.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    {% block css %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <style>
        ::-webkit-scrollbar {
            width: 10px;
            height: 10px;
            border-radius: 5px;
        }

        ::-webkit-scrollbar-track {
            background-color: #f1f1f1;
            border-radius: 5px;
        }

        ::-webkit-scrollbar-thumb {
            background-color: var(--color-lightgray);
            border-radius: 5px;
        }

        ::-webkit-scrollbar-thumb:hover {
            background-color: var(--color-lightergray);
        }
    </style>
</head>
<body>
<header>
    <div class="header-container">
        <a href="{% url 'main:main' %}" class="site-title">
            <h1 class="brand-name">
                <span>Название</span>
            </h1>
        </a>
        <button class="navbar-toggle">&#9776;</button>
        <div class="header-buttons">
            <button class="add-trip" id="addButton">Добавить поездку</button>
            {% if user.is_authenticated %}
                <button class="profile" id="profileButton">Профиль</button>
            {% else %}
                <button class="login" id="loginButton">Вход/Регистрация</button>
            {% endif %}
        </div>
    </div>
</header>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Перенаправление на страницу входа/регистрации
        document.getElementById('loginButton')?.addEventListener('click', function() {
            window.location.href = "{% url 'main:login' %}";
        });

        // Перенаправление на страницу профиля
        document.getElementById('profileButton')?.addEventListener('click', function() {
            window.location.href = "{% url 'main:profile' %}";
        });

        // Переключение навбара
        document.querySelector('.navbar-toggle').addEventListener('click', function() {
            document.querySelector('.header-buttons').classList.toggle('active');
        });

        // Перенаправление при нажатии на кнопку "Добавить поездку"
        document.getElementById('addButton').addEventListener('click', function() {
            {% if user.is_authenticated %}
                window.location.href = "{% url 'main:add_trip' %}";
            {% else %}
                window.location.href = "{% url 'main:register' %}";
            {% endif %}
        });
    });
</script>
{% block content %}
{% endblock %}

{% block catalog %}
{% endblock %}

{% block footer %}
{% endblock %}
</body>
</html>

traveling/main/templates/main/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    {% block css %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}

{% block catalog %}
{% endblock %}

{% block footer %}
{% endblock %}
</body>
</html>

traveling/main/templates/main/login.html
{% extends "main/base1.html" %}
{% load static %}

{% block css %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Roboto:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'main/register.css' %}">
{% endblock %}

{% block title %}
Регистрация
{% endblock %}

{% block content %}
<div class="container">
    <div class="image-side">
        <img src="{% static 'img/reg_img.jpg' %}" alt="Car Image">
    </div>
    <div class="form-side">
        <h1>Добро пожаловать, <br> авторизуйтесь в <span>Название</span></h1>
        <p>Введите ваши данные ниже</p>
        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <label for="email">Email</label>
            <input type="email" id="email" name="email" placeholder="ivanivanov@gmail.com" value="{{ form.data.email|default_if_none:'' }}">
            {{ form.errors.email }}


            <label for="password">Пароль</label>
            <input type="password" id="password" name="password" placeholder="********">
            {{ form.errors.password }}

            <div class="links-container">
                <a href="{% url 'main:main' %}">Назад</a>
                <a href="{% url 'main:register' %}">Зарегистрироваться</a>
            </div>

            <button type="submit">Авторизоваться</button>
        </form>
    </div>
</div>
{% endblock content %}

traveling/main/templates/main/register.html
{% extends "main/base1.html" %}
{% load static %}

{% block css %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Roboto:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'main/register.css' %}">
<script src="https://cdn.jsdelivr.net/npm/cleave.js/dist/cleave.min.js"></script>
{% endblock %}

{% block title %}
Регистрация
{% endblock %}

{% block content %}
<div class="container">
    <div class="image-side">
        <img src="{% static 'img/reg_img.jpg' %}" alt="Car Image">
    </div>
    <div class="form-side">
        <h1>Добро пожаловать, <br> зарегистрируйтесь в <span>Название</span></h1>
        <p>Введите ваши данные ниже</p>
        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <label for="name">Имя и фамилия</label>
            <input type="text" id="name" name="name" placeholder="Иван Иванов" value="{{ form.data.name|default_if_none:'' }}">
            {{ form.errors.name }}

            <label for="email">Email</label>
            <input type="email" id="email" name="email" placeholder="ivanivanov@gmail.com" value="{{ form.data.email|default_if_none:'' }}">
            {{ form.errors.email }}

            <label for="phone">Номер телефона</label>
            <input type="tel" id="phone" name="phone" placeholder="+7 (900) 123 45 67" value="{{ form.data.phone|default_if_none:'' }}">
            {{ form.errors.phone }}

            <label for="password">Пароль</label>
            <input type="password" id="password" name="password" placeholder="********">
            {{ form.errors.password }}

            <div class="links-container">
                <a href="{% url 'main:main' %}">Назад</a>
                <a href="{% url 'main:login' %}">Войти</a>
            </div>

            <button type="submit">Зарегистрироваться</button>
        </form>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        new Cleave('#phone', {
            prefix: '+',
            numericOnly: true
        });
    });
</script>
{% endblock content %}

traveling/main/templates/main/trip_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for trip in trips %}
    <div class="trip">
        <h3>{{ trip.departure_city.name }} - {{ trip.destination_city.name }}</h3>
        <p>Дата: {{ trip.departure_date }}</p>
        <p>Цена: {{ trip.price }} ₽</p>
        <p>Максимальное количество пассажиров: {{ trip.max_passengers }}</p>
    </div>
{% endfor %}
</body>
</html>